### ISSUE TITLE
Swift 3 version

### ISSUE THREAD

**Issue by AmitaiB** [ManueGE/Actions#1]
Is there any chance of a Swift 3 update soon?

**Comment by ManueGE** [comment]
As son as I can. I will try tomorrow :)

**Comment by ManueGE** [comment]
I made the changes but I am having some problems uploading the pod. 

In the meantime, you can do it by adding this line to your `Podfile`: 

```
pod 'Actions', :git => 'https://github.com/ManueGE/Actions.git', :tag => 'swift_3'
```

**Comment by ManueGE** [comment]
It's already done :). The swift version has been uploaded. It is the version 2.0.0, so you would need to do a `pod update`.

**Comment by AmitaiB** [comment]
Awesome! And very impressive turnaround time, also. ;)
